# Generated by Django 5.2.8 on 2026-07-24 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['-created_at'], 'verbose_name': 'Party', 'verbose_name_plural': 'Parties'},
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['party_name'], name='app_party_party_n_28355e_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['mobile_number'], name='app_party_mobile__f20a22_idx'),
        ),
    ]
